import NavBar from "../../components/NavBar";
import Header from "../../components/Header";
import Footer from "../../components/Footer";
import ScrollToTop from "../../components/ScrollToTop";

const Intention = () => {
	return (
		<div>
			<NavBar />
			<Header title="Intention and Inspiration" />
			<div className="blog-text-container">
				<h4>Intention</h4>
				<div className="header-bars"></div>

				<p>
					The intention for my final internet art is to create an artwork that
					speaks to the important questions of AI generated artwork and content.{" "}
				</p>
				<p>
					So on the website all the images will be generated by an AI algorithm
					using OpenAI. All placeholder images (currently white circles and
					blocks) will be replaced by this AI generated content. The goal is to
					have a user experience the website as if they were just looking at
					normal curator’s website that has primarily chosen its focus to be
					queer African art. But upon closer inspection they will realise that
					all the artwork is AI generated.
				</p>
				<p>
					This brings up many important questions central to which is the way
					that we classify and label art, we expect certain things when we hear
					certain words, so for example, if one said futuristic art there’s a
					certain image that comes to mind, and if one said classical art
					another set of conventions come to mind. AI plays on this because it
					uses algorithms and historical data of the things we classify as
					specific kinds of art to generate something that would generically fit
					into that criteria we have arbitrarily set.
				</p>
				<p>
					Whilst I do not wish to engage on the good or bad of having
					conventions so set in stone that a computer could create something
					that fits so easily and convincingly into that convention, I do want
					to engage with the fact that African queer art is not a genre or a
					convention but rather a categorisation of art made by certain kinds if
					people, and it is very broad and diverse in nature.
				</p>
				<p>
					So to highlight this I will actually have a section on my website, the
					artists page where the user can see and engage with actual art made by
					actual queer artists. And see how broad how varied the artwork is, as
					well as be able to contrast it with what the AI produces.
				</p>
				<p>
					For me the most standout part about the conversation between ai
					generated and human art is the simple fact that computers cannot be
					creative. They can regurgitate mixtures and variations of what exists,
					but the ability to think and imagine and create out of the box, to
					fight and query convention is solely human. And herein lies the
					superiority of human art.
				</p>
				<p>
					Hence in the neoliberal capitalist world we find ourselves, where it
					is almost certain that in years to come, we will witness more and more
					corporations opting to steal and regurgitate the art styles and works
					of human artists by having an AI algorithm generate imitations of
					their art instead of actually paying the artists to do the work. One
					thing is certain, the AI will never be creative. In the wise words of
					a TikTok meme sound “you can’t beat the original, see you in hell
					bitch.”
				</p>

				<h4>Inspiration</h4>
				<div className="header-bars"></div>
				<p>
					I began my journey of making internet art at the same time that AIs
					like ChatGPT were taking a hold of public discourse, so like any
					curious artists I became interest in what this meant for the art world
					and had a lot of fun generating artwork using these AIs.{" "}
				</p>
				<p>
					But soon the lawsuits and artists claiming their art was stolen came
					to rise and with this the realisation that these cool computers that
					can make art were actually not making art in the same sense that we as
					humans conceptualise the idea of making art. And that prompted my
					thinking.
				</p>
				<p>
					So my first attempt at making an internet art was to simply get a
					simple page, that had AI generated art and content but present to the
					user without telling them this. It is in this presentation that I
					found a space that needed to be explored, exactly how do I present
					this art.
				</p>
				<p>
					Previously it was just on a white background and a very simple
					minimalistic website. But then I got the idea from my tutor Iman to
					actually make the website be a statement in itself not just an empty
					container for the art. And so I began to brainstorm and look around
					for what other websites that curated art seemed to do.
				</p>
				<p>
					The first thing that I noticed was that the best websites often spoke
					to the kinds of art they were curating. So the font and colour scheme
					and overall design matched or complimented the art style of the art
					shown on the website. Going forward I will be talking about ‘African
					art’ not a true representative or descriptor of what African art is
					but in the sense of how African art is conceptualised and categorised
					by many people.
				</p>
				<p>
					In my case I felt that bold saturated colours and the incorporation of
					geometric patterns spoke really well to the African artistic context.
					A lot of African art invokes bright colours and geometric patterns.
				</p>

				<div>
					{/* <picture>
						<img
							alt=""
							src={require("../../assets/pattern1.jpg")}
							className="blog-hero-image"
						/>
					</picture>
					<picture>
						<img
							alt=""
							src={require("../../assets/pattern2.webp")}
							className="blog-hero-image"
						/>
					</picture> */}
					{/* <picture>
						<img
							alt=""
							src={require("../../assets/pattern3.jfif")}
							className="blog-hero-image"
						/>
					</picture> */}
				</div>

				<p>
					I did not of course want to veer too far into bright colours and
					patterns that would clutter the website and clash with the art, so I
					decided to go for a light pink background (I just wanted to get away
					from the plain white background without using a heavy colour) that has
					white geometric patterns on it.
				</p>
				<p>
					At the moment the patterns are spaced out and placed at random, but in
					future I will explore the possibility of having the patterns be more
					repetitive ordered.
				</p>
				<p>These are the patterns and the background.</p>
				<div>
					{/* <picture>
						<img
							alt=""
							src={require("../../assets/Illustrations Patterns.png")}
							className="blog-hero-image"
						/>
					</picture> */}
				</div>

				<p>
					And here’s an image of the patterns I drew up but on a darker
					background so they can more easily
				</p>
				<div>
					{/* <picture>
						<img
							alt=""
							src={require("../../assets/Illustrations Patterns 1.png")}
							className="blog-hero-image"
						/>
					</picture> */}
				</div>

				<p>
					In terms of making the patterns I took a lot of inspiration from the
					south African fashion brand
					<a href="https://shop.maxhosa.africa/" className="blog-link">
						{" "}
						Maxhosa.
					</a>{" "}
					Their use of patterns in their latest collection really stood out to
					me and the kinds of patterns I made drew heavily from this.
				</p>

				<div>
					{/* <picture>
						<img
							alt=""
							src={require("../../assets/maxhosa1.webp")}
							className="blog-inspiration-image"
						/>
					</picture>
					<picture>
						<img
							alt=""
							src={require("../../assets/maxhosa2.webp")}
							className="blog-inspiration-image"
						/>
					</picture>
					<picture>
						<img
							alt=""
							src={require("../../assets/maxhosa3.webp")}
							className="blog-inspiration-image"
						/>
					</picture>
					<picture>
						<img
							alt=""
							src={require("../../assets/maxhosa4.webp")}
							className="blog-inspiration-image"
						/>
					</picture> */}
				</div>

				<p>
					I got the idea of encapsulating the artwork and images on the site in
					circular borders from this enhance artist’s design for a{" "}
					<a
						href="https://www.behance.net/gallery/140159313/Website-of-the-Prado-National-Museum-Concept"
						className="blog-link"
					>
						{" "}
						national art museum.
					</a>{" "}
					It really made the art stand out and highlighted the colours existing
					in the images. I decided however that I did not want the circular
					borders containing the art to be even in circumference, I wanted it to
					be a bit more whimsical and lopsided because ethe art it would be
					containing was not structured in the same way western classical art
					was. The art the AI generated had a certain uncanniness to it and
					often lacked structure and balance. So to play into this I made my
					circular borders uneven.
				</p>

				<div>
					{/* <picture>
						<img
							alt=""
							src={require("../../assets/Picture1.png")}
							className="blog-inspiration-image"
						/>
					</picture>
					<picture>
						<img
							alt=""
							src={require("../../assets/Picture2.png")}
							className="blog-inspiration-image"
						/>
					</picture> */}
				</div>

				<p>
					My navigation and header styles were drawn from{" "}
					<a
						href="https://www.behance.net/gallery/162883759/Classical-Photography-Gallery-Web-Design"
						className="blog-link"
					>
						{" "}
						this site.
					</a>{" "}
				</p>

				<div>
					{/* <picture>
						<img
							alt=""
							src={require("../../assets/Picture3.png")}
							className="blog-inspiration-image"
						/>
					</picture> */}
				</div>

				<p>
					And finally, I got the idea to add a shop section from a lot of the
					other websites because they were made for institutions with financial
					incentives so a lot of these either sell tickets to the exhibitions if
					there are physical exhibitions available or they sell merchandise.
				</p>
				<p>
					And I felt it might add to the credibility of the site if this section
					did exist and it would also begin speaking to the financial
					implications of AI generated content.
				</p>

				<div>
					{/* <picture>
						<img
							alt=""
							src={require("../../assets/Picture4.png")}
							className="blog-inspiration-image"
						/>
					</picture> */}
				</div>

				<p>
					The entire Behance mood board I used for inspiration with the
					collection of websites that inspired me can be{" "}
					<a
						href="https://www.behance.net/collection/204306417/Internet-Art"
						className="blog-link"
					>
						{" "}
						found here.
					</a>{" "}
				</p>

				<h4>Going Forward</h4>
				<div className="header-bars"></div>

				<p>
					Going forward I will be working to add the AI generator to the website
					and add the ai generated art to fill in the spaces. I will also be
					populating the shop with three products; I might actually make the
					three products depending on time and take pictures of those if not I
					will just use mock-ups.{" "}
				</p>

				<p>
					Then I will be populating my artists page to show the artworks and
					artists that are making art and are queer and African.
				</p>
			</div>

			<ScrollToTop />
			<Footer />
		</div>
	);
};

export default Intention;
